### ISSUE TITLE
Upgrade to GeoServer Cloud 1.8.3

### ISSUE THREAD

**Issue by groldan** [camptocamp/helm-geoserver-cloud#216]
Upgrade to [1.8.3](https://github.com/geoserver/geoserver-cloud/releases/tag/v1.8.3).

## What's changed

Some improvements and fixes backported from the main (1.9-SNAPSHOT) development branch.

### Improvements

https://github.com/geoserver/geoserver-cloud/commit/f77ae33ae683e8087c99aae0b885a1d1a29c8103 share webui authentication with the other services through the gateway
https://github.com/geoserver/geoserver-cloud/commit/63d0e775874ca18407e8f410f967284bca58c991 Build LayerGroupContainmentCache's cache asynchronously

### Bug fixes

https://github.com/geoserver/geoserver-cloud/commit/82e7d26e7cf21db842887c07b11f9c5525378b3a Fix gateway root URI with missing trailing / redirect to webui
https://github.com/geoserver/geoserver-cloud/commit/5e1ee96230f0f5414c926af08e3f22fdb78dd3fc Fix RepositoryCatalogFacadeImpl's query of PublishedInfo.class

### Misc

https://github.com/geoserver/geoserver-cloud/commit/dc5e7e2e64a62632f40e1b07a52d78c7cf86bf85 General code clean up

**Comment by jemacchi** [comment]
@groldan please check release 1.8.3. It's not working as expected in context of use with ACL.
ie. log as admin, create 2 layers, do not create associated ACL rules, try to access with preview, and it renders them (while it should fail). If you log out then layers are not listed in preview. If you access again and enable/allow access to one of layers in ACL, then if you log out and check preview list, you will be able to see it listed (while the other one it wont be listed, but when logged as admin you can access both of the layers).
It works as expected when listing layers in preview list, but it's not hiding/blocking layers access as it's supposed.

**Comment by jemacchi** [comment]
btw, tested same case with 1.8.2 (used in latest release of the helmchart), and works as expected (so problem is on 1.8.3)

**Comment by jemacchi** [comment]
Based on talk, I see that behavior should be as expected then, as it's covered in this fix  https://github.com/geoserver/geoserver-cloud/pull/474

1. When logged as admin, it does not matter the ACLs rules (since it's allowed). So the preview under that session is enabled even when no rules are created.
2. When logged as any other user, then ACL rules are applied.

The mentioned PR fixed the situation of anonymous preview when logged as admin in webui (my bad not understand that from the notes)

Helmchart new release created https://github.com/camptocamp/helm-geoserver-cloud/releases/tag/2.1.1

**Comment by groldan** [comment]
That's a feature, not a bug.

I've been waiting years to say that :)

**Comment by jemacchi** [comment]
is it a feature that fix a behavior you were not agree with ? a feature fix, LOL
